<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-NVUIMMA" ignored="0" name="Default test" tests="14" failures="1" timestamp="14 四月 2020 15:48:57 GMT" time="125.639" errors="0">
  <testcase name="idSubmitInfo" time="39.48" classname="com.wecash.http.cases.identitySubmit">
    <failure type="java.lang.AssertionError" message="expected [50003693145221335302000100100512020-04-10 16:33:552020-04-10 16:33:55] but found [693145221335302000]">
      <![CDATA[java.lang.AssertionError: expected [50003693145221335302000100100512020-04-10 16:33:552020-04-10 16:33:55] but found [693145221335302000]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.wecash.http.cases.identitySubmit.idSubmitInfo(identitySubmit.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- idSubmitInfo -->
  <testcase name="idSubmitInfo" time="37.265" classname="com.wecash.http.cases.identitySubmit"/>
  <testcase name="idSubmitInfo" time="39.433" classname="com.wecash.http.cases.identitySubmit"/>
  <testcase name="idSubmitInfo" time="0.476" classname="com.wecash.http.cases.identitySubmit"/>
  <testcase name="idSubmitInfo" time="0.477" classname="com.wecash.http.cases.identitySubmit"/>
  <testcase name="idSubmitInfo" time="0.465" classname="com.wecash.http.cases.identitySubmit"/>
  <testcase name="idSubmitInfo" time="0.501" classname="com.wecash.http.cases.identitySubmit"/>
  <testcase name="idSubmitInfo" time="0.479" classname="com.wecash.http.cases.identitySubmit"/>
  <testcase name="idSubmitInfo" time="0.614" classname="com.wecash.http.cases.identitySubmit"/>
  <testcase name="idSubmitInfo" time="0.603" classname="com.wecash.http.cases.identitySubmit"/>
  <testcase name="idSubmitInfo" time="0.456" classname="com.wecash.http.cases.identitySubmit"/>
  <testcase name="idSubmitInfo" time="0.488" classname="com.wecash.http.cases.identitySubmit"/>
  <testcase name="idSubmitInfo" time="0.486" classname="com.wecash.http.cases.identitySubmit"/>
  <testcase name="idSubmitInfo" time="0.476" classname="com.wecash.http.cases.identitySubmit"/>
</testsuite> <!-- Default test -->
