<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-NVUIMMA" name="com.wecash.http.cases.JobPut" tests="25" failures="2" timestamp="17 四月 2020 12:21:08 GMT" time="346.004" errors="0">
  <testcase name="SaveJobInfo" time="16.237" classname="com.wecash.http.cases.JobPut"/>
  <testcase name="SaveJobInfo" time="15.919" classname="com.wecash.http.cases.JobPut"/>
  <testcase name="SaveJobInfo" time="16.340" classname="com.wecash.http.cases.JobPut"/>
  <testcase name="SaveJobInfo" time="0.453" classname="com.wecash.http.cases.JobPut"/>
  <testcase name="SaveJobInfo" time="15.960" classname="com.wecash.http.cases.JobPut"/>
  <testcase name="SaveJobInfo" time="16.206" classname="com.wecash.http.cases.JobPut"/>
  <testcase name="SaveJobInfo" time="0.440" classname="com.wecash.http.cases.JobPut"/>
  <testcase name="SaveJobInfo" time="16.204" classname="com.wecash.http.cases.JobPut"/>
  <testcase name="SaveJobInfo" time="16.527" classname="com.wecash.http.cases.JobPut"/>
  <testcase name="SaveJobInfo" time="16.554" classname="com.wecash.http.cases.JobPut"/>
  <testcase name="SaveJobInfo" time="16.257" classname="com.wecash.http.cases.JobPut"/>
  <testcase name="SaveJobInfo" time="16.223" classname="com.wecash.http.cases.JobPut"/>
  <testcase name="SaveJobInfo" time="16.357" classname="com.wecash.http.cases.JobPut"/>
  <testcase name="SaveJobInfo" time="16.101" classname="com.wecash.http.cases.JobPut"/>
  <testcase name="SaveJobInfo" time="0.437" classname="com.wecash.http.cases.JobPut"/>
  <testcase name="SaveJobInfo" time="20.249" classname="com.wecash.http.cases.JobPut">
    <failure type="java.lang.AssertionError" message="expected [2020-04-17 20:15:39] but found [2020-04-17 20]">
      <![CDATA[java.lang.AssertionError: expected [2020-04-17 20:15:39] but found [2020-04-17 20]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.wecash.http.cases.JobPut.SaveJobInfo(JobPut.java:107)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- SaveJobInfo -->
  <testcase name="SaveJobInfo" time="0.448" classname="com.wecash.http.cases.JobPut"/>
  <testcase name="SaveJobInfo" time="16.158" classname="com.wecash.http.cases.JobPut"/>
  <testcase name="SaveJobInfo" time="15.756" classname="com.wecash.http.cases.JobPut"/>
  <testcase name="SaveJobInfo" time="16.275" classname="com.wecash.http.cases.JobPut"/>
  <testcase name="SaveJobInfo" time="16.181" classname="com.wecash.http.cases.JobPut"/>
  <testcase name="SaveJobInfo" time="15.897" classname="com.wecash.http.cases.JobPut"/>
  <testcase name="SaveJobInfo" time="16.268" classname="com.wecash.http.cases.JobPut">
    <failure type="java.lang.AssertionError" message="expected [000113,,] but found [000113,IT,test,shanyin]">
      <![CDATA[java.lang.AssertionError: expected [000113,,] but found [000113,IT,test,shanyin]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.wecash.http.cases.JobPut.SaveJobInfo(JobPut.java:63)
at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- SaveJobInfo -->
  <testcase name="SaveJobInfo" time="16.109" classname="com.wecash.http.cases.JobPut"/>
  <testcase name="SaveJobInfo" time="16.448" classname="com.wecash.http.cases.JobPut"/>
</testsuite> <!-- com.wecash.http.cases.JobPut -->
